# don't build tags, it's redundant

language: node_js
node_js:
  - 12
cache:
  npm: true
  directories:
    - ~/.cache
before_install:
  - npm i -g npm@latest
install: npm install
script:
  - npm run build || travis_terminate 1;
