name: deployDocs
on:
  push:
    branches:
      - deploy-docs-action
    paths:
      - '.github/**'
jobs:
  deploy-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm run deployDocs
